
apiVersion: v1
kind: Service
metadata:
  name: trend-app-lb
  namespace: default
 
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: trend-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
